language: python
python:
  - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev" # 3.5 development branch
  # - "nightly" # currently points to 3.6-dev

install:
  - pip install    coverage coveralls
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script: nosetests --with-coverage --cover-erase --cover-package=feedpipe

after_success:
  coveralls
